<?php

namespace AppBundle\Repository;

/**
 * RedditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedditRepository extends \Doctrine\ORM\EntityRepository
{
}
